name: flutter_ble_sandbox
description: "A flutter BLE experiment"

version: 1.0.0+1

environment:
  sdk: '>=3.4.3'

dependencies:
  android_intent: ^2.0.2
  flutter:
    sdk: flutter
  flutter_reactive_ble: ^5.3.1
  permission_handler: ^11.3.1
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
